export const STR = {
  title: "BLOCK OPS",
  chapter: "NIGHT RUNS",
  subtitle: "Equity Uprise · Bridgeport after dark",
  tapToStart: "START THE SHIFT",
  keysHint: "WASD point the whip · mouse aims the turret, hold to fire · SPACE nitro · E smoke · Q spikes",
  touchHint: "Left stick drives · right stick aims & fires · gold = nitro · chips drop smoke & spikes",
  shift: "SHIFT",
  rep: "REP",
  best: "BEST",
  streak: "STREAK",
  onFire: "ON FIRE",
  pickup: "PICK UP",
  dropoff: "DROP",
  carrying: "CARRYING",
  hot: "HOT ZONE +",
  delivered: "DELIVERED",
  spotted: "SPOTTED — LOSE THEM",
  clear: "YOU LOST THEM",
  shiftDone: "SHIFT CLEARED",
  clockedOut: "THE NIGHT TOOK IT",
  runAgain: "RUN IT BACK",
  newBest: "NEW BEST",
  next: "ROLL OUT →",
  shopTitle: "THE RE-UP — spend your REP",
  shopSkip: "Keep it moving →",
  filed: "✓ filed to your record — the tape reads it at 9:07",
  filedAnon: "sign in on the floor and these runs bank real game points",
  up_engine: "Engine Work",
  up_engine_d: "+7% top speed",
  up_plate: "Street Plating",
  up_plate_d: "+25 max health",
  up_cool: "Nitro Cooling",
  up_cool_d: "-20% nitro cooldown",
  up_smoke: "Smoke Kit ×2",
  up_smoke_d: "Drop a cloud — cones can't see through it",
  up_spike: "Spike Strips ×2",
  up_spike_d: "Drop behind you — pops a chaser for 3s",
  up_turret: "Heavy Bass",
  up_turret_d: "+20% turret damage",
  smoke: "SMOKE",
  spikes: "SPIKES",
  nitro: "NITRO",
};

/* the storyline: every shift is a page of the real ecosystem — the
   members are real, the lore is real, the receipts are real */
export const SHIFTS = [
  { from: "Equity Uprise", tick: "EU",
    line: "The city sleeps on its artists. You don't. Three packages tonight — no headlines, no headlights." },
  { from: "Only Us Studios", tick: "OUST",
    line: "Ocho's masters leave the studio tonight. The crews would love to hold them hostage. Don't let a cone touch you." },
  { from: "The Street Credit Bureau", tick: "SCB",
    line: "The tape writes itself at 9:07 — these files make the snapshot or they don't exist. The Bureau pays for punctual." },
  { from: "Hitman Benji", tick: "BENJI",
    line: "Word is the crews know your plates now. They're looking harder. Smoke's in the trunk for a reason." },
  { from: "The Community Fund", tick: "FUND",
    line: "Tonight's cut feeds the chest — artist development, education, the culture. Every drop lands twice." },
  { from: "The Exchange", tick: "XCHG",
    line: "Every run you finish is on your record, and the floor reads receipts. Your line moves when you move." },
];
