export const STR = {
  title: "BLOCK OPS",
  subtitle: "Equity Uprise · the tactical block",
  tapToStart: "TAP TO RUN THE BLOCK",
  keysHint: "WASD move · mouse aim · hold to fire · SPACE dash",
  touchHint: "Left stick move · right stick aim & fire · gold button dash",
  wave: "WAVE",
  rep: "REP",
  best: "BEST",
  streak: "STREAK",
  onFire: "ON FIRE",
  contractPickup: "GRAB THE PACKAGE",
  contractDrop: "RUN IT TO THE DROP",
  delivered: "DELIVERED",
  waveCleared: "BLOCK CLEARED",
  shopTitle: "RE-UP — spend your REP",
  shopSkip: "Keep it moving →",
  clockedOut: "CLOCKED OUT",
  runAgain: "RUN IT BACK",
  newBest: "NEW BEST",
  paused: "PAUSED",
  up_speed: "Fast Money",
  up_speed_d: "+8% move speed",
  up_damage: "Heavy Bass",
  up_damage_d: "+20% cannon damage",
  up_dash: "Slick Moves",
  up_dash_d: "-15% dash cooldown",
  up_hp: "Thick Skin",
  up_hp_d: "+20 max health",
  up_rate: "Rapid Delivery",
  up_rate_d: "+15% fire rate",
  overdrive: "OVERDRIVE",
  medkit: "PATCHED UP",
};
